#!/bin/bash -e

PREFIX=""

if [ -z $CI ]; then
  PREFIX="venv/bin/"

  if [ ! -d venv ]; then
    set -x
    python -m venv venv
    ${PREFIX}pip install -U pip setuptools wheel
  fi
fi

set -x
${PREFIX}pip install -r requirements.txt
